apiVersion: v1
kind: Service
metadata:
  name: jekflix-service
spec:
  type: NodePort
  selector:
    app: jekflix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
